### ISSUE TITLE
type `&std::path::Path` does not implement any method in scope named `to_owned`

### ISSUE THREAD

**Issue by TimoDritschler** [alexcrichton/gcc-rs#58]
The library does not compile for me with the following error messages
```
   Compiling gcc v0.3.18
/home/dritscht/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.18/src/lib.rs:268:46: 268:56 error: type `&std::path::Path` does not implement any method in scope named `to_owned`
/home/dritscht/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.18/src/lib.rs:268         self.out_dir = Some(out_dir.as_ref().to_owned());
                                                                                                                                      ^~~~~~~~~~
/home/dritscht/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.18/src/lib.rs:268:56: 268:56 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
/home/dritscht/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.18/src/lib.rs:268:56: 268:56 help: candidate #1: use `collections::borrow::ToOwned`
/home/dritscht/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.18/src/lib.rs:278:48: 278:58 error: type `&std::path::Path` does not implement any method in scope named `to_owned`
/home/dritscht/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.18/src/lib.rs:278         self.compiler = Some(compiler.as_ref().to_owned());
                                                                                                                                        ^~~~~~~~~~
/home/dritscht/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.18/src/lib.rs:278:58: 278:58 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
/home/dritscht/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.18/src/lib.rs:278:58: 278:58 help: candidate #1: use `collections::borrow::ToOwned`
/home/dritscht/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.18/src/lib.rs:288:48: 288:58 error: type `&std::path::Path` does not implement any method in scope named `to_owned`
/home/dritscht/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.18/src/lib.rs:288         self.archiver = Some(archiver.as_ref().to_owned());
                                                                                                                                        ^~~~~~~~~~
/home/dritscht/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.18/src/lib.rs:288:58: 288:58 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
/home/dritscht/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.18/src/lib.rs:288:58: 288:58 help: candidate #1: use `collections::borrow::ToOwned`
/home/dritscht/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.18/src/lib.rs:303:35: 303:45 error: type `&std::ffi::os_str::OsStr` does not implement any method in scope named `to_owned`
/home/dritscht/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.18/src/lib.rs:303         self.env.push((a.as_ref().to_owned(), b.as_ref().to_owned()));
                                                                                                                           ^~~~~~~~~~
/home/dritscht/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.18/src/lib.rs:303:45: 303:45 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
/home/dritscht/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.18/src/lib.rs:303:45: 303:45 help: candidate #1: use `collections::borrow::ToOwned`
/home/dritscht/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.18/src/lib.rs:303:58: 303:68 error: type `&std::ffi::os_str::OsStr` does not implement any method in scope named `to_owned`
/home/dritscht/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.18/src/lib.rs:303         self.env.push((a.as_ref().to_owned(), b.as_ref().to_owned()));
                                                                                                                                                  ^~~~~~~~~~
/home/dritscht/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.18/src/lib.rs:303:68: 303:68 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
/home/dritscht/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.18/src/lib.rs:303:68: 303:68 help: candidate #1: use `collections::borrow::ToOwned`
error: aborting due to 5 previous errors
Could not compile `gcc`.
```

I'm using rust version 1.0.0-beta (9854143cb 2015-04-02) (built 2015-04-02) and the current ```master``` branch of gcc-rs (0.3.18)
OS is OpenSUSE 13.1 (Kernel 3.11.10-29-desktop)

Any ideas?
Thanks!

P.S.: I'm using 0.3.13 (3a44fddc) for now, which does not include the to_owned() changes yet

**Comment by alexcrichton** [comment]
Thanks for the report! The version of the compiler you're using is quite old (pre-1.0!) which is why this isn't compiling (this lib only works on 1.0+). Would it be possible to update `rustc` for you?

**Comment by TimoDritschler** [comment]
Yeah, you were right! My ```rustup.sh``` script was outdated and did not pull the 1.3.0 stable branch of the compiler. With the correct compiler, it all works fine. Thank you!
